Traceback (most recent call last):
  File "train.py", line 89, in <module>
    main(config)
  File "train.py", line 67, in main
    trainer.train()
  File "/home/xinyuzhao/faultModel/src/base/base_trainer.py", line 61, in train
    result = self._train_epoch(epoch)
  File "/home/xinyuzhao/faultModel/src/trainer/fault_trainer.py", line 52, in _train_epoch
    origin,injected=FaultInject.weight_inject(self.fault,self.model)
  File "/home/xinyuzhao/faultModel/src/playground/corrupt.py", line 41, in weight_inject
    else:
TypeError: 'Fault' object is not iterable

real	4m3.681s
user	5m30.940s
sys	2m3.635s
